# Generated by Django 5.2 on 2025-04-29 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='ServiceAvailability',
        ),
    ]
