# Generated by Django 5.2 on 2025-05-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partyconstructor',
            old_name='budget_from',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='partyconstructor',
            name='budget_to',
        ),
    ]
